// ============================================
// GENERATED BY ML TRAINING PIPELINE (train.py)
// DO NOT EDIT DIRECTLY
// ============================================

export const trainedModel = {
  "healthScoreModel": {
    "importances": {
      "Financial Literacy": 49.4,
      "Repayment History": 13.5,
      "Risk Management": 37.1
    },
    "intercept": 33.39685811673935,
    "coefficients": [
      18.309160519852323,
      -6.295647216043062,
      -1.66149240658972,
      -0.32415323216486014,
      -3.494927921696563,
      0.5305189891568187,
      0.9589119585681092,
      2.2869416748324403,
      -8.783757755850546,
      5.714268646922872,
      1.162152736909558,
      4.272487022717705
    ]
  },
  "defaultRiskModel": {
    "lakshmiRiskScore": 9.2,
    "nabardStats": {
      "Business": {
        "default_rate": 19.1,
        "risk_level": "Medium"
      },
      "Car": {
        "default_rate": 20.2,
        "risk_level": "Medium"
      },
      "Debt consolidation": {
        "default_rate": 20.1,
        "risk_level": "Medium"
      },
      "Education": {
        "default_rate": 22.2,
        "risk_level": "Medium"
      },
      "Home": {
        "default_rate": 17.6,
        "risk_level": "Medium"
      },
      "Medical": {
        "default_rate": 21.7,
        "risk_level": "Medium"
      },
      "Other": {
        "default_rate": 19.7,
        "risk_level": "Medium"
      },
      "Vacation": {
        "default_rate": 20.8,
        "risk_level": "Medium"
      }
    }
  },
  "commodityPrices": {
    "Maize": {
      "current_price": 2153.0,
      "history": [
        1938.0,
        1981.0,
        2024.0,
        2067.0,
        2110.0,
        2153.0
      ],
      "forecast": [
        2196.0,
        2229.0,
        2261.0
      ]
    },
    "Paddy(Dhan)(Common)": {
      "current_price": 3000.0,
      "history": [
        2700,
        2750,
        2800,
        2850,
        2900,
        3000
      ],
      "forecast": [
        3050,
        3100,
        3150
      ]
    },
    "Tomato": {
      "current_price": 1228.0,
      "history": [
        1105.0,
        1130.0,
        1154.0,
        1179.0,
        1203.0,
        1228.0
      ],
      "forecast": [
        1252.0,
        1271.0,
        1289.0
      ]
    },
    "Onion": {
      "current_price": 896.0,
      "history": [
        806.0,
        824.0,
        842.0,
        860.0,
        878.0,
        896.0
      ],
      "forecast": [
        913.0,
        927.0,
        940.0
      ]
    }
  }
};
