import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function PortfolioPage() {
    const sectors = [
        { name: 'Agri-Logistics & Cold Storage', count: 18, exposure: '₹7.2 Cr', avgCvi: 36, avgGvs: 78 },
        { name: 'Renewable Bioenergy & Solar', count: 12, exposure: '₹9.4 Cr', avgCvi: 24, avgGvs: 89 },
        { name: 'Coastal Aquaculture', count: 7, exposure: '₹2.8 Cr', avgCvi: 68, avgGvs: 56 },
        { name: 'Textiles & Dyeing', count: 5, exposure: '₹3.6 Cr', avgCvi: 52, avgGvs: 64 },
    ];
    return (_jsxs("div", { className: "space-y-6 animate-fade-in", children: [_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-white tracking-tight", children: "Portfolio Climate Risk & Stress Analytics" }), _jsx("p", { className: "text-sm text-slate-400 mt-0.5", children: "Aggregated exposure, hazard concentration, and green asset transition metrics across all branches" })] }), _jsx("div", { className: "flex items-center gap-2", children: _jsxs("button", { className: "px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium rounded-lg border border-slate-700 flex items-center gap-1.5 cursor-pointer", children: [_jsx("span", { className: "material-symbols-outlined text-sm", children: "download" }), "Export BRSR / TCFD Report"] }) })] }), _jsxs("div", { className: "rounded-xl bg-slate-900/60 border border-slate-800 p-5 space-y-4", children: [_jsx("h2", { className: "text-base font-semibold text-white", children: "Sectoral Climate Risk & Green Allocation" }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-left text-xs", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-slate-800 text-slate-400 bg-slate-950/40", children: [_jsx("th", { className: "py-3 px-4 font-semibold", children: "Sector" }), _jsx("th", { className: "py-3 px-4 font-semibold", children: "Active Loans" }), _jsx("th", { className: "py-3 px-4 font-semibold", children: "Total Exposure" }), _jsx("th", { className: "py-3 px-4 font-semibold text-center", children: "Avg CVI Score" }), _jsx("th", { className: "py-3 px-4 font-semibold text-center", children: "Avg GVS Score" }), _jsx("th", { className: "py-3 px-4 font-semibold text-right", children: "Risk Profile" })] }) }), _jsx("tbody", { className: "divide-y divide-slate-800/60", children: sectors.map((s, idx) => (_jsxs("tr", { className: "hover:bg-slate-800/30 transition-colors", children: [_jsx("td", { className: "py-3.5 px-4 font-semibold text-slate-100", children: s.name }), _jsx("td", { className: "py-3.5 px-4 text-slate-300", children: s.count }), _jsx("td", { className: "py-3.5 px-4 text-slate-200 font-medium", children: s.exposure }), _jsx("td", { className: "py-3.5 px-4 text-center", children: _jsxs("span", { className: `inline-block px-2 py-0.5 rounded text-[10px] font-bold ${s.avgCvi <= 30 ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' :
                                                        s.avgCvi <= 55 ? 'bg-amber-500/10 text-amber-400 border border-amber-500/20' :
                                                            'bg-red-500/10 text-red-400 border border-red-500/20'}`, children: [s.avgCvi, "/100"] }) }), _jsx("td", { className: "py-3.5 px-4 text-center", children: _jsxs("span", { className: "inline-block px-2 py-0.5 rounded text-[10px] font-bold bg-brand-500/10 text-brand-400 border border-brand-500/20", children: [s.avgGvs, "/100"] }) }), _jsx("td", { className: "py-3.5 px-4 text-right", children: _jsx("span", { className: "text-[11px] text-slate-400 font-medium", children: s.avgCvi > 55 ? 'Needs Climate Adaptation' : 'Transition Aligned' }) })] }, idx))) })] }) })] })] }));
}
//# sourceMappingURL=PortfolioPage.js.map